### ISSUE TITLE
Lights on pods stay on when docker is unpluged

### ISSUE THREAD

**Issue by Eric-Dorflinger** [Plantiga/FirmwareDockerBase#6] opened 2019-10-04 21:35 UTC
Pod lights stay on when docked even after dock is unplugged. When taking one pod off after the doc is unplugged the remaining pod stays lit, and if you put the pod back on it will light up again. If both pods are taken off before putting either one back on the doc, the lights will not turn back on if docked again.

![2](https://user-images.githubusercontent.com/55894022/66241409-dba3f280-e6b3-11e9-9dc4-298179e60b2d.jpg)

**Comment by kaypenney** [comment] 2019-10-07 18:39
duplicate of #279

**Closed as completed by kaypenney** 2019-10-07 18:39 UTC
Labels: bug
